name: License Notice

description: Standard license acknowledgment for AGPL v3.0

body:
  - type: markdown
    attributes:
      value: |
        ### License Notice

        This project is licensed under GNU AGPL v3.0.

        See the LICENSE file for full terms and conditions.

  - type: checkboxes
    attributes:
      label: Acknowledgment
      description: Confirm you understand the license.
      options:
        - label: I understand this software is licensed under GNU AGPL v3.0
        - label: I will comply with the AGPL license terms



